CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE,
  "email" varchar UNIQUE,
  "hashed_password" varchar,
  "avatar_path" varchar
);

CREATE TABLE "tokens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "value" varchar UNIQUE
);

CREATE TABLE "compositions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "visibility" varchar,
  "creator_id" int,
  "blueprint_id" int
);

CREATE TABLE "composition_blueprints" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_id" int,
  "creator_id" int,
  "time_created" timestamp,
  "value" varchar
);

CREATE TABLE "composition_editors" (
  "composition_id" int,
  "user_id" int,
  PRIMARY KEY ("composition_id", "user_id")
);

CREATE TABLE "samples" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "path" varchar
);

CREATE TABLE "melodies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "keyboard_id" int,
  "name" varchar,
  "blueprint" varchar
);

CREATE TABLE "keyboards" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "keyboard_samples" (
  "keyboard_id" int,
  "sample_id" int,
  "key_index" int,
  PRIMARY KEY ("keyboard_id", "sample_id")
);

CREATE TABLE "user_samples" (
  "user_id" int,
  "sample_id" int,
  PRIMARY KEY ("user_id", "sample_id")
);

CREATE TABLE "favourite_users" (
  "user_id" int,
  "favourite_user_id" int,
  PRIMARY KEY ("user_id", "favourite_user_id")
);

CREATE TABLE "favourite_compositions" (
  "user_id" int,
  "favourite_composition_id" int,
  PRIMARY KEY ("user_id", "favourite_composition_id")
);

ALTER TABLE "melodies" ADD FOREIGN KEY ("keyboard_id") REFERENCES "keyboards" ("id");

ALTER TABLE "keyboard_samples" ADD FOREIGN KEY ("sample_id") REFERENCES "samples" ("id");

ALTER TABLE "keyboard_samples" ADD FOREIGN KEY ("keyboard_id") REFERENCES "keyboards" ("id");

ALTER TABLE "compositions" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");

ALTER TABLE "composition_editors" ADD FOREIGN KEY ("composition_id") REFERENCES "compositions" ("id");

ALTER TABLE "composition_editors" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "compositions" ADD FOREIGN KEY ("blueprint_id") REFERENCES "composition_blueprints" ("id");

ALTER TABLE "composition_blueprints" ADD FOREIGN KEY ("parent_id") REFERENCES "composition_blueprints" ("id");

ALTER TABLE "tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_samples" ADD FOREIGN KEY ("sample_id") REFERENCES "samples" ("id");

ALTER TABLE "user_samples" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "favourite_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "favourite_users" ADD FOREIGN KEY ("favourite_user_id") REFERENCES "users" ("id");

ALTER TABLE "favourite_compositions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "favourite_compositions" ADD FOREIGN KEY ("user_id") REFERENCES "compositions" ("id");

ALTER TABLE "composition_blueprints" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");
